name       : perl-test-most
version    : 0.35
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/O/OV/OVID/Test-Most-0.35.tar.gz : 9897a6f4d751598d2ed1047e01c1554b01d0f8c96c45e7e845229782bf6f657f
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Most commonly needed test functions and features
description: |
    Most commonly needed test functions and features. This module provides you with the most commonly used testing functions and gives you a bit more fine-grained control over your test suite.
builddeps  :
    - perl-exception-class
    - perl-test-deep
    - perl-test-differences
    - perl-test-exception
    - perl-test-warn
rundeps    :
    - perl-exception-class
    - perl-test-deep
    - perl-test-differences
    - perl-test-exception
    - perl-test-warn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
