name       : perl-test-most
version    : '0.38'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/O/OV/OVID/Test-Most-0.38.tar.gz : 089eb894f7bace4c37c6334e0e290eb20338ee10223af0c82cbe7281c78382df
homepage   : https://metacpan.org/pod/Test::Most
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Most - Most commonly needed test functions and features
description: |
    Test::Most exists to reduce boilerplate and to make your testing life easier. We provide "one stop shopping" for most commonly used testing modules. In fact, we often require the latest versions so that you get bug fixes through Test::Most and don't have to keep upgrading these modules separately.
builddeps  :
    - perl-exception-class
    - perl-test-deep
    - perl-test-differences
    - perl-test-exception
    - perl-test-warn
rundeps    :
    - perl-exception-class
    - perl-test-deep
    - perl-test-differences
    - perl-test-exception
    - perl-test-warn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
